### ISSUE TITLE
apiManual and local generation lower quality then api

### ISSUE THREAD

**Issue by wingzx3** [daswer123/xtts-api-server#13]
I found that if you change the local_generation function to use the following inference call it will match the api voice.
```
        out = self.model.inference(
            text,
            language,
            gpt_cond_latent=gpt_cond_latent,
            speaker_embedding=speaker_embedding,
            temperature=0.75,
            length_penalty=1.0,
            repetition_penalty=5.0,
            top_k=50,
            top_p=0.85,
            enable_text_splitting=True
        )
```
I copied the temperature, length_penalty, repetition_penalty, top_k, top_p from the config.json in the model directory.

**Comment by daswer123** [comment]
Hey, thanks, I fixed it.

**Comment by daswer123** [comment]
apiManual uses the same settings as the API , the only difference is that apiManual uses model version 2.0.2.
