### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by woCmodsiW** [daswer123/xtts-api-server#14]
python -m venv venv
source venv/bin/activate

Should be placed in the installation instructions for Linux users. I just attempted to upgrade/install and everything flew by installing without creating an environment. I have no idea if this has broken other dependencies and I _just_ recovered from a difficult upgrade.

May I suggest you please keep a development version separate while you work on new pull requests/updates?

**Comment by daswer123** [comment]
Yeah I was just testing a couple things, failed miserably, of course I'll fix it now )

**Comment by woCmodsiW** [comment]
> Yeah I was just testing a couple things, failed miserably, of course I'll fix it now )

Things are really really bad on my install now.
Doing simple install leads to errors on Linux for me.

I now have a cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
>_>

**Comment by woCmodsiW** [comment]
> Check out the instructions in the repo with a similar install, it's all detailed there https://github.com/KoljaB/RealtimeTTS#cuda-installation



> Check out the instructions in the repo with a similar install, it's all detailed there https://github.com/KoljaB/RealtimeTTS#cuda-installation

I think I'm just going to take a break from this repo until you get everything in order.
Hopefully a pip uninstall xtts-api-server will fix things because as I mentioned... my dependencies are odd now.

I should have never updated.
