### ISSUE TITLE
How do I set it so it runs on the GPU?

### ISSUE THREAD

**Issue by GGame666** [daswer123/xtts-api-server#15]
I realize it is probably a dumb question but I can't figure out how to run it on my GPU.  I am running it on Windows

**Comment by daswer123** [comment]
Hi, make sure you have torch installed with support for where.
`pip install torch==2.1.1.1+cu118 torchaudio==2.1.1.1+cu118 --index-url https://download.pytorch.org/whl/cu118`

If you don't have CUDA on your system, follow this guide
https://github.com/KoljaB/RealtimeTTS#cuda-installation

**Comment by daswer123** [comment]
It's okay, there shouldn't be a problem

**Comment by GGame666** [comment]
Thank you it works but I don't know what caused it but it was probably that I ran the cmd from that tasks bar and not from the folder. but either way thank you for the fast responses
