### ISSUE TITLE
RealtimeXTTS needs to be updated to v0.3.31 to fix --streaming voices from WAV.

### ISSUE THREAD

**Issue by strawberrymelonpanda** [daswer123/xtts-api-server#17]
See bug details [here](https://github.com/KoljaB/RealtimeTTS/issues/18).

Specifically the fix seems to be changing 
`filename = filename[:-4]` to `filename = filename[:-3]` 

on line 143 of coqui_engine.py.  After replacing with the updated files from the RealtimeXTTS and running `pip install . --upgrade`, it was working correctly for me, otherwise I'd only get the default voice.

**Comment by daswer123** [comment]
Hi, thanks for letting me know.
I have updated the RealtimeTTS lib to 3.3.32 this should fix the problem
