### ISSUE TITLE
Error while downloading the model (first start)

### ISSUE THREAD

**Issue by Talref** [daswer123/xtts-api-server#2]
After running:
python -m xtts_api_server

` File "/home/eradan/miniconda3/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='coqui.gateway.scarf.sh', port=443): Max retries exceeded with url: /hf-coqui/XTTS-v2/main/model.pth (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1007)')))
`

**Comment by Talref** [comment]
PiHole was blocking the domain

**Comment by daswer123** [comment]
Hi, glad the problem's solved.
