### ISSUE TITLE
Audio playback in group chats

### ISSUE THREAD

**Issue by Sascha353** [daswer123/xtts-api-server#21]
Wen you are in a group chat (tested with two characters) and both answer to the same question, only the second one will be played fully. The first one is either cut off or doesn't start at all. I'm not sure if audio inference itself is interrupted by the second request or just the playback. Also I'm not sure if it is a problem with my configuration, SillyTavern or xtts-api-server.

The xtts-api-server shows the following output:
`INFO:     ::1:49923 - "POST /tts_to_audio/ HTTP/1.1" 200 OK`
`INFO:     ::1:49923 - "POST /tts_to_audio/ HTTP/1.1" 200 OK`

I noticed that for both posts "49923" is used, could this be related?

In theory, if it is caused by xtts-api-server do we just need to pause while an audio stream is active?

This is how I start the server:

`Python.exe -m xtts_api_server -d "cuda" -sf MODELS -o RECORDING -ms "local" -v 2.0.2 --streaming-mode-improve`

**Comment by daswer123** [comment]
I tested and yes indeed it can be fixed but then the characters can't be silenced they will talk until they finish, if you want I can add such a setting, in the kind of a flag

**Comment by Sascha353** [comment]
Interesting, I wasn't aware of the interrupt feature. How is it designed to work? Interrupt as soon as the second reply comes in or is it triggered by some sort of interrupt flag? What I can say for sure is that in my case the answer of the second reply was referring to information from the first reply, which wasn't even said yet. However it was already written, so in this case it felt wrong to interrupt. Is there any logic behind the interrupt? The best would be obviously to differentiate between a correct or incorrect interruption. If this is not possible I'd prefer to deactivate it, as it feels wrong in my case, during a normal dialog where only the second answer comes through, so a flag would be very welcome.,

**Comment by daswer123** [comment]
The way it works is that when it gets a new request it interrupts the current one and starts a new one, if you use what I was talking about then all requests will be referenced in the queue.

There are some problems with the fact that streaming is still replaying the last request, so to make it work properly, you need to turn streaming off

## Before:

https://github.com/daswer123/xtts-api-server/assets/22278673/70198884-88e2-4d8a-a86a-da32fbc317ae

## After

https://github.com/daswer123/xtts-api-server/assets/22278673/e577b460-d7df-422c-99fb-b22d0b01256f

**Comment by Sascha353** [comment]
I see, without streaming there is no interruption but it's also slower to respond for larger text. Is it still viable to have an "wait for audio queue"-flag for streaming mode?

**Comment by daswer123** [comment]
I use the RealtimeTTS library and a similar mechanism is already implemented there.

As for the speed reduction, in general the reduction is not very strong and as I understand it happens because it waits until all threads are finished and only then starts the next processing from the queue.

Added flag `--stream-play-sync` it should be used with other flags for streaming mode.

**Comment by daswer123** [comment]
Fixed, also added deepspeed support this should speed up processing and start playing the first phrase, you need to add flag `---deepspeed`.

That's right, it finishes before it plays audio, unfortunately it can't continue to synthesize audio further as it waits for the current stream to finish.

**Comment by Sascha353** [comment]
Can confirm, both streaming modes with `--stream-play-sync` work, as well as `--deepspeed`. Cool stuff.
