### ISSUE TITLE
Implementing support for speakers with multiple speaker_wav files

### ISSUE THREAD

**Issue by lendot** [daswer123/xtts-api-server#23]
This is mostly informational; I'm not seeing a Discussion link for this repo, so hopefully it's ok to post this here.

I don't see it mentioned much, but xtts allows one to provide multiple 6-second speaker_wav files, which it then averages together when synthesizing the text. I've found this to be really helpful in getting certain cloned voices closer to the source. I really wanted to try this out in SillyTavern so I decided to take a stab at adding this functionality to xtts_api_server. You can see what I have so far at [my fork](https://github.com/lendot/xtts-api-server/tree/sample-wav-multiple)

_Note_: this is very incomplete as of this writing and not ready for the masses, but I wanted to at least mention it now in case anyone wants to give it a whirl and let me know if there are any problems.

Existing single-file speakers work just as they have. If you want to add a speaker with multiple speaker_wavs, just create a directory in `speakers/` with the name of your speaker and dump all their speaker_wav files in there. If you're previewing a multi-wav speaker in extensions, it'll play whichever wav file it found in that directory first. This doesn't yet work with streaming mode. Likewise, only `--model-source local` (the default) works.

**Comment by daswer123** [comment]
Hi, good job.

I'll check it out later, thanks for the contribution :)

**Comment by lendot** [comment]
It now works with Realtime and I fixed a couple other odds and ends.

**Comment by daswer123** [comment]
Cool, if you want to make a PR, I'd be glad to merge it.

**Comment by daswer123** [comment]
Merge your PR, now it's available to everyone. thanks for contibution

**Comment by daswer123** [comment]
I think we can close this issue, if there is anything left to say, you can open new issues
