### ISSUE TITLE
Short term caching

### ISSUE THREAD

**Issue by Xyem** [daswer123/xtts-api-server#25]
Would you consider adding (or a PR to add) a small cache so if the same parameters are requested, it will return the recently created output, rather than generating it again? Experimenting with RVC settings in SillyTavern would be much more smooth if it did this.

**Comment by daswer123** [comment]
If I understand correctly, you want that if the parameters of the request matches the previous generation, then the server gives the ready file that was created earlier?

In general, this can be done, if I understand you correctly.

**Comment by Xyem** [comment]
Yes, I'm suggesting something like [memoisation](https://en.wikipedia.org/wiki/Memoization). Even if it was just the previous request as you say, this would be very helpful, but perhaps some others would like a slightly larger cache (or even a configurable one) if it as just as easy to implement?

**Comment by daswer123** [comment]
Done, now you can use the `--use-cache` flag this will cache all results until the server restarts

**Comment by Xyem** [comment]
I updated and tested this and it works great for what I needed. Thank you so much for adding this!

**Comment by daswer123** [comment]
That's great.
