### ISSUE TITLE
Did not see a link to your discord

### ISSUE THREAD

**Issue by MackNcD** [daswer123/xtts-api-server#26]
Is there a link to your discord on your xtts apps anywhere? I apologize if I just happened to pass over it

**Comment by daswer123** [comment]
This project is not big enough to have a discord, if you want you can discuss in the official Coque group in discord. 
https://discord.gg/uzPMEpM7Gv

**Comment by MackNcD** [comment]
> This project is not big enough to have a discord, if you want you can discuss in the official Coqui AI ( XTTS creators ) group in discord. https://discord.gg/uzPMEpM7Gv

Okay do you have screen name on that server? I've been working with the API/DiceWords (an original program by yours truly,) and I've since decided to choose a single voice for the read outs and want to fine tune it, but have been having trouble getting a fine tune model to load up outside of collab. It trains/loads on collab, and trains but simply will not load up locally. I figured if there's someone to review things with as I head into this portion of the program, it'd be you, and obviously I'd name and link you and you will get the additional credit as the project transitions from prompts only to a larger note-lab (portable sudo-write, is the vision).
