### ISSUE TITLE
Typo: spekaer_name_or_path

### ISSUE THREAD

**Issue by acidbubbles** [daswer123/xtts-api-server#27]
Here's the typo: https://github.com/daswer123/xtts-api-server/blob/13e03383acd3754281e1e73117ec44f06be2c770/xtts_api_server/tts_funcs.py#L349

Error: `xtts_api_server.server:tts_to_audio:243 - name 'spekaer_name_or_path' is not defined`

Thanks for packaging xtts by the way, I tried it from Coqui and it was messy :D

**Comment by daswer123** [comment]
Thanks for letting me know, I've fixed it
