### ISSUE TITLE
-hs 0.0.0.0 breaks preview_url

### ISSUE THREAD

**Issue by lendot** [daswer123/xtts-api-server#28]
if listening on 0.0.0.0, then the preview_url created in get_speakers_special is http://0.0.0.0:8020/sample/foo.wav, which is bogus as far as any client is concerned. I've been getting around this by giving -hs the explicit ip address on that machine I'll be talking to it on, which is fine for my purposes but not overly robust.

I"m not quite sure how this _should_ be handled, but one idea would be to use the Host: header in the HTTP request to form the preview URL.. That way if a machine with two or more interfaces is running xtts_api_server -hs 0.0.0.0, Host should in most cases tell you which one the client has reached/is intending to talk to.

**Comment by daswer123** [comment]
Yes, I know about this problem, so I added a special flag -t URL , this flag allows you to specify the address that will be used for the preview

**Comment by lendot** [comment]
Ah! Ok. I misunderstood the purpose of that flag. Suggestion: if someone does -hs 0.0.0.0 and doesn't provide a -t, log some sort of warning telling them that previews will break unless they set a tunnel.

I'd still argue for doing something like the Host solution I mentioned though as it's both more elegant and more robust. A _ton_ of servers out there have some form of "--listen 0.0.0.0" so there should be some generally accepted best practices for URL construction. When I get a few minutes I"ll take a look around and see what folks are doing, as I'm curious in general.

**Comment by daswer123** [comment]
I added a `--listen` flag and also made it automatically detect the local ip address of the computer so that I don't have to write the -t flag, this should make it easier to use the server outside the local pc.
