### ISSUE TITLE
Wav files not loading

### ISSUE THREAD

**Issue by Revenn555** [daswer123/xtts-api-server#29]
I managed to connect server to mobile version of SillyTavern, because instead of a red error, when I press "Reload", the text "Successfully applied settings Select TTS Provider" appears. Only wav recordings do not appear in Available voices. After a while, red "Could not load voices" appears. How to fix this? My wav file is in the "speakers" folder.

This is my folder
![RDT_20231222_2327241191680028301250043](https://github.com/daswer123/xtts-api-server/assets/104529621/9cbccf58-b3cb-4b7f-8e14-0d39300da261)

And this is running server 
![RDT_20231222_2327182768013694486925900](https://github.com/daswer123/xtts-api-server/assets/104529621/7113e855-ec4a-47cf-990f-40a68d49eff8)

**Comment by daswer123** [comment]
Look, if you run xtts-api-server on your computer and use it on your phone, you need to do the following things:
1) Add flag `-hs 0.0.0.0.0` , in phone you need to specify ip address of your computer in local network.
2) Next, find the ip address of your computer in the local network (for example 192.168.1.10) and add the flag `-t 192.168.1.10`.
3) As a result you will be able to use the server inside the local network and receive wav files on demand.

It could look like this:
On a computer `xtts_api_server -hs 0.0.0.0.0 -t 192.168.1.10`.
On the phone you enter: `192.168.1.10:8020`.

**Comment by Revenn555** [comment]
I type on cmd "python -m xtts_api_server -hs 0.0.0.0.0 -t (my ip iv4) --deepspeed" but i have error
![Bez tytułu](https://github.com/daswer123/xtts-api-server/assets/104529621/4ebcbb5d-d421-4770-ad5c-4d85e66ce526)

**Comment by daswer123** [comment]
> -hs 0.0.0.0.0

you have an extra 0 in `-hs`

should be `python -m xtts_api_server -hs 0.0.0.0 -t (my ip iv4) --deepspeed`

**Comment by Revenn555** [comment]
You're right, the 0 and the dot were unnecessary, now I'm connected. Thanks for the help, one more question, because I noticed that the text generation itself takes a lot longer, is it because I have the XTTS server and text generation webui running at the same time? Is there any way to speed this up?

**Comment by daswer123** [comment]
You can optionally use the `--lowvram` flag , this should reduce total idle memory utilization

**Comment by Revenn555** [comment]
Because I was wondering whether I should just reduce the load on the PC and run the colab version, but as far as I know, the API mode does not support --deepspeed

**Comment by daswer123** [comment]
It supports, you can try colab, only streaming-mode doesn't work in colab, `--streaming-mode`.

**Comment by Revenn555** [comment]
When i chose api in colab, and check deepspeed after a load this show of
"xtts_api_server.server:<module>:42 - You are using deepspeed, it only works with model source local, the model source is automatically changed to local" what is this mean? If i chose api and deepspeed this automaticali change to local?

**Comment by daswer123** [comment]
I wrote incorrectly, it means that not ready-made methods will be used, but local methods for inference.

It's okay, I'll correct the description a bit later

**Comment by Revenn555** [comment]
Thank You for helping, i finally after few days connect and run this server and all works fine. I consider the topic closed

**Comment by daswer123** [comment]
Great, glad it worked out for you :)
