### ISSUE TITLE
error installing tts mojimoji

### ISSUE THREAD

**Issue by ExoZNiK** [daswer123/xtts-api-server#3]
Hi, i followed the istrucionts on sillytavern documents and i got this error when i do the command "pip install xtts-api-server".

All components installed well until these lines:

"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD "-IC:\Users\ExoZ NiK\AppData\Local\Temp\pip-build-env-076xj5q_\overlay\Lib\site-packages\numpy\core\include" "-IC:\Users\ExoZ NiK\AppData\Local\Programs\Python\Python310\include" "-IC:\Users\ExoZ NiK\AppData\Local\Programs\Python\Python310\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /TcTTS/tts/utils/monotonic_align/core.c /Fobuild\temp.win-amd64-cpython-310\Release\TTS/tts/utils/monotonic_align/core.obj
      core.c
      C:\Users\ExoZ NiK\AppData\Local\Programs\Python\Python310\include\pyconfig.h(59): fatal error C1083: Non Š possibile aprire il file inclusione: 'io.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tts
  Building wheel for mojimoji (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for mojimoji (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\mojimoji
      copying mojimoji\__init__.pyi -> build\lib.win-amd64-cpython-310\mojimoji
      copying mojimoji\py.typed -> build\lib.win-amd64-cpython-310\mojimoji
      running build_ext
      building 'mojimoji' extension
      creating build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD "-IC:\Users\ExoZ NiK\AppData\Local\Programs\Python\Python310\include" "-IC:\Users\ExoZ NiK\AppData\Local\Programs\Python\Python310\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /EHsc /Tpmojimoji.cpp /Fobuild\temp.win-amd64-cpython-310\Release\mojimoji.obj
      mojimoji.cpp
      C:\Users\ExoZ NiK\AppData\Local\Programs\Python\Python310\include\pyconfig.h(59): fatal error C1083: Non Š possibile aprire il file inclusione: 'io.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mojimoji
Failed to build tts mojimoji
ERROR: Could not build wheels for tts, mojimoji, which is required to install pyproject.toml-based projects

What could be the problem?

**Comment by daswer123** [comment]
Hello, 
this issue occurs because the Microsoft Visual C++ compiler cannot find the 'io.h' file. This is usually caused by incomplete installation or incorrect configuration of the build tools

Try re-installing Microsoft C++ Build Tools

**Comment by ExoZNiK** [comment]
i runned just a moment before installing the "vs_buildtool.exe" which updated my visualstudio build tools to version 17.8.1. Should i try to do Repair into the program or maybe i'm missing a component isnide the program that i have not checked into the boxes?

**Comment by daswer123** [comment]
It should be by default, try Repair

**Comment by ExoZNiK** [comment]
i tried with repair and now when i restarted over the whole guide i got stuck at the command "conda activate xtts".
the outpust error is this:

C:\AI\xtts>conda activate xtts
usage: conda-script.py [-h] [-v] [--no-plugins] [-V] COMMAND ...
conda-script.py: error: argument COMMAND: invalid choice: 'activate' (choose from 'clean', 'compare', 'config', 'create', 'info', 'init', 'install', 'list', 'notices', 'package', 'remove', 'uninstall', 'rename', 'run', 'search', 'update', 'upgrade', 'doctor', 'repoquery', 'env', 'content-trust')

what am i doing wrong? -.-'

**Comment by daswer123** [comment]
I don't use conda it's kinda difficult to tell, I make a little guide to python venv 

https://github.com/daswer123/xtts-api-server/assets/22278673/67918529-5ffe-49f0-b5ba-2aa7677fd974

Create a folder and open the cmd or powershell in it.
Then enter the command
1) `python -m venv venv`
2) `venv/scripts/activate`
3) `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`
4) `pip install xtts-api-server`
5) `python -m xtts_api_server`

If you want to start the server again, then open the console and do item 2 and 5

**Comment by ExoZNiK** [comment]
Thank you very much for your guide and video! Awesome! The reapir seems to be worked anyway, i don't know why updating the old version made it go wrong... I wish it would be used instead of conda in the sillytavern official docs... that would be easier and not require another probgram like conda... Conda seems to be solved just by adding another command line before all the other...

Just to tell if someone run into the same error: "call C:\AI\miniconda3\Scripts/activate.bat C:\AI\miniconda"

Of course it must be adjusted accordingly if someone has a different path. Anyway now all seems to work! (didn't try with a voice because i don't have a wav file for now...)

Just another question, it work even if the sillytavern extras are not working at the same time or sillytavern extras must be connected to make this api server work?

Great job and help anyway! :)

**Comment by daswer123** [comment]
sillytavern extras are not needed, just api server is enough

**Comment by daswer123** [comment]
> ! (didn't try with a voice because i don't have a wav file for now...)

You can use the sample voice from here https://github.com/daswer123/xtts-api-server/tree/main/example

**Comment by ExoZNiK** [comment]
tried and it worked nice! The language in sillytavern must be put into the language of the text to narrate or based on the voice used in the peakers wav audio?

**Comment by daswer123** [comment]
According to my observations, the language of the sample does not matter, it will be similar to itself in all languages, especially the one in which the sample is made.

The language in the SillyTavern settings affects only the pronunciation, if you select English, the English text will have a British accent, if you select French on the English text, it will have a French Accent, I advise you to experiment with this.

**Comment by ExoZNiK** [comment]
Ok thanks for the explanation and the deteiled guide with the video! Amazing job!
