### ISSUE TITLE
Error Installing 

### ISSUE THREAD

**Issue by Sylensar** [daswer123/xtts-api-server#31]
Im getting a certain error when trying to run the 3rd and foruth command.

Error: To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

(venv) E:\ST\SillyTavern\xtts>pip install torch==2.1.1+cu118 torchaudio==2.1.1+cu118 --index-url https://download.pytorch.org/whl/cu118
Looking in indexes: https://download.pytorch.org/whl/cu118
ERROR: Could not find a version that satisfies the requiremen

**Comment by daswer123** [comment]
It looks like you have either python 3.12 or <3.9. You need to reinstall python to version 3.10 or 3.11

**Comment by Sylensar** [comment]
@daswer123 Ohhhh Okay, will do now.
