### ISSUE TITLE
Output folder

### ISSUE THREAD

**Issue by Magicalore** [daswer123/xtts-api-server#39]
Hi,

I'm trying to find the generated audio files from the Sillytavern conversation. I used the --output argument and input the output folder but no sound files are generated anywhere even if I input another folder. How could I find/create the folder where the wav audio files are generated? Thanks

**Comment by daswer123** [comment]
Hi, Sillytavern uses an endpoint that does not save files, however you can use the `--use-cache` flag, it will save all generations

**Comment by Magicalore** [comment]
Hi thanks for the answer, I tried it but it only now creates a cache.json file of 1kb (with just "{}" inside) but not aujdio files

**Comment by Magicalore** [comment]
Nevermind, for some reason it works now thanks so much for your work! <3
