### ISSUE TITLE
ERROR: No matching distribution found for xtts-api-server

### ISSUE THREAD

**Issue by samliu315** [daswer123/xtts-api-server#4]
Sorry for asking such a basic question, but I can't install it. How can I solve this?
Looking in indexes: https://mirrors.cloud.tencent.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement xtts-api-server (from versions: none)
ERROR: No matching distribution found for xtts-api-server

**Comment by daswer123** [comment]
https://pypi.org/project/xtts-api-server/

Everything is in place, try again

**Comment by samliu315** [comment]
I tried +==0.3.2 installing , and it worked.

**Comment by samliu315** [comment]
I tried +==0.3.2 installing , and it worked.
