### ISSUE TITLE
"python.exe: No module named xtts_api_server"

### ISSUE THREAD

**Issue by Nezumi-exe** [daswer123/xtts-api-server#44]
Apologize I'm a noob at this, but am trying to get this up and running. I followed all the steps for windows install, but I run into this message whenever I try to start the api server.

![brave_saHMEh7dzx](https://github.com/daswer123/xtts-api-server/assets/4240036/bcbf09ee-599d-43d3-a3bb-985b49fec13a)

What am I doing wrong?

**Comment by daswer123** [comment]
Hi, it looks like the xtts-api-server module is not installed, try installing everything again

**Comment by Nezumi-exe** [comment]
> Hi, it looks like the xtts-api-server module is not installed, try installing everything again

ok i fixed it thx
