### ISSUE TITLE
TTS has a problem of repeatedly downloading models, which needs to be solved by updating tts to v0.21.1

### ISSUE THREAD

**Issue by samliu315** [daswer123/xtts-api-server#5]
https://github.com/oobabooga/text-generation-webui/issues/4723

**Comment by daswer123** [comment]
Hi, was busy yesterday, already updated everything today
https://github.com/daswer123/xtts-api-server/issues/7#issuecomment-1827332333

**Comment by samliu315** [comment]
Nice work !
