### ISSUE TITLE
Re the readme bit on your front page.

### ISSUE THREAD

**Issue by erew123** [daswer123/xtts-api-server#7]
I originally wrote it. I was wrong and it does want 22050Hz input files, but outputs at 24000Hz. So you may want to change it to the below (I changed it on Reddit already, have revised it below for you! & thanks for linking my post).

Also, people need to update their TTS https://github.com/oobabooga/text-generation-webui/issues/4723#issuecomment-1826120220

The 2.0.3 model sounds rubbish by the way... so people will want to stick with the 2.0.2 model

Thanks!

```
Some suggestions on making good samples

Keep them about 7-9 seconds long. Longer isn't necessarily better.

Make sure the audio is down sampled to a Mono, 22050Hz 16 Bit wav file. You will slow down processing by a large % and it seems cause poor quality results otherwise (based on a few tests). 24000Hz is the quality it outputs at anyway!

Using the latest version of Audacity, select your clip and Tracks > Resample to 22050Hz, then Tracks > Mix > Stereo to Mono. and then File > Export Audio, saving it as a WAV of 22050Hz

-If you need to do any audio cleaning, do it before you compress it down to the above settings (Mono, 22050Hz, 16 Bit).

Ensure the clip you use doesn't have background noises or music on e.g. lots of movies have quiet music when many of the actors are talking. Bad quality audio will have hiss that needs clearing up. The AI will pick this up, even if we don't, and to some degree, use > it in the simulated voice to some extent, so clean audio is key!

Try make your clip one of nice flowing speech, like the included example files. No big pauses, gaps or other sounds. Preferably one that the person you are trying to copy will show a little vocal range. Example files are in \text-generation- >webui\extensions\coqui_tts\voices

Make sure the clip doesn't start or end with breathy sounds (breathing in/out etc).

Using AI generated audio clips may introduce unwanted sounds as its already a copy/simulation of a voice, though, this would need testing.
```

**Comment by daswer123** [comment]
Thanks again , I took some samples of your code and `modeldowloader.py`.
https://github.com/oobabooga/text-generation-webui/issues/4712#issuecomment-1825593734

You can update xtts-api-server 
`pip install --upgrade xtts-api-server`

Now model 2.0.2 will be downloaded by default and TTS version will also be checked at startup.

Added a new flag, `-ms [repo,local]` 
Which indicates in what format you want to use xtts
`local` - will download the model version 2.0.2 in the folder models. 
`repo` - will download the latest version of the model.

The default is `local`, so you don't need to set the flag additionally.

**Comment by erew123** [comment]
Hey! Thanks for your replies etc :) You clearly know how to code (I'm not a coder, other than to have bit of a play). 

They definitely do have a different sound. In the code I am working on for Text-Gen-WebUI, I was going to give everyone the choice in the interface as to which method they want to use. Its a work in progress and Ill be dumping updates to the code as I go.  Thanks for the pointer to your code! That's just what I was looking for today! :)

I might be implementing a config file of some kind to store all the (variables/base/model to use and download) settings people use and other things. Ill let you know as/when I've got some tidy code to look at. I will be posting it back in the same place.

I also use SillyTavern, so thanks for getting XTTS working on there. The low VRAM method I have implemented in my code is very useful for people with very little VRAM to spare (less than 2GB when their LLM is loaded in) https://github.com/oobabooga/text-generation-webui/issues/4712#issuecomment-1825309021. Very simply, all that does is:

- When the XTTS engine starts up, don't load the model into memory.
- When you generate TTS, it loads the model into VRAM, which forces a few layers of your LLM model to unload from VRAM temporarily. 
- This allows the whole TTS model to have enough space to load into your VRAM, which speeds up processing by a factor of 4-5 for people who have less than 2GB of VRAM free after loading their LLM. (see my images on the link I gave above)
- It then unloads the TTS model and the layers of your LLM load back into VRAM within 1-2 seconds, so hardly causes any slowdown for your LLM.

You might like to implement something like that in your code as an option for people. I suspect, because you are already running in your own separate python environment from the one that the LLM is loaded into, it would be nothing more than doing a load and unload of the model as/when TTS is requested/finished.

**Comment by erew123** [comment]
I spotted something in both our codebases.... In yours its here:

`tts_func.py`
```
    def api_generation(self,text,speaker_wav,language,output_file):
        self.model.tts_to_file(
                text=text,
                speaker_wav=speaker_wav,
                language=language,
                file_path=output_file  # Assuming tts_to_file takes 'file_path' as an argument.
        )
```
split_sentences=True

https://tts.readthedocs.io/en/latest/models/xtts.html#single-reference

You may have chosen to leave it off. But you know the bit where if it reads a really long paragraph, by the end of the paragraph, it starts to sound strange OR you see the "this message is over to 250 character limit", this is what works around that. It also means you use more VRAM when processing TTS if you have it Disabled...... though I suspect if its enabled, it may take a bit longer to generate TTS.

Sorry if you've worked around it another way, I spotted in my own code and thought Id check yours for you too, but I haven't read through all your code! :)

**Comment by daswer123** [comment]
The tts_to_file is a method for the API, inside this method there is already a mechanism for splitting sentences.

![image](https://github.com/daswer123/xtts-api-server/assets/22278673/4b327125-93e5-4513-b2c4-c85ff832f94f)

Split_sentences is needed if you create a config and synthesize locally

https://github.com/daswer123/xtts-api-server/blob/4505c79ad00e5ed9c8469d00b07bb0968c1ea83a/xtts_api_server/tts_funcs.py#L203C36-L203C36

**Comment by erew123** [comment]
I thought that too, however, I haven't yet tested this. I have however seen the warning message a few times about my messages being too long, and best I could understand, forcing that setting on *may* resolve it. I need to go back and read some more! 

Ill let you know if find out anything! :) 

Thanks again!

**Comment by erew123** [comment]
Looks like they have updated TTS engine to v0.21.2 and v0.21.3 https://github.com/coqui-ai/TTS/discussions/3340

The v0.21.2 has updates for text splitting within the engine.

**Comment by daswer123** [comment]
Great info, definitely worth upgrading the requirements to >=0.21.2

**Comment by deffcolony** [comment]
hi @daswer123 the xtts api works great
I made a automation script that installs and setup all requirements for XTTS i use it together with [sillytavern ](https://github.com/SillyTavern/SillyTavern) and here is the script i made 
https://github.com/SillyTavern/SillyTavern-Launcher/blob/4889ecb717a25b0744a88074c0f1f43535f173d9/installer.bat#L213

**Comment by daswer123** [comment]
Hi, glad to hear that my project is useful, you have a good project too :)

**Comment by erew123** [comment]
@daswer123 Hey! Hope you are well! Not sure these can be included with the software, I don't know what level of creative commons they are, but, if you want another 40 voices https://www.file.io/YeR7/download/3RR3Nzx6acnO 

Some of them are mixed quality, but generally they work ok.

**Comment by erew123** [comment]
@daswer123 Changed the link to here, turns out that link only let 1x person download them https://filebin.net/t97nd69ac7qm2rsf

**Comment by daswer123** [comment]
@erew123 Hi, thanks for sharing, I've added the information to the README
